### ISSUE TITLE
sdk-client-v2 build fails because it can't find the buffer module

### ISSUE THREAD

**Issue by alessandro-calo-emma** [commercetools/commercetools-sdk-typescript#166]
I just upgraded from `sdk-client` to `sdk-client-v2`, going directly to version `1.0.1`.
When building my node project, I get:

```
Error: Cannot find module 'buffer/'
Require stack:
- .../node_modules/@commercetools/sdk-client-v2/dist/commercetools-sdk-client-v2.cjs.dev.js
- .../node_modules/@commercetools/sdk-client-v2/dist/commercetools-sdk-client-v2.cjs.js
- ...
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (/Users/alessandro/Documents/Emma/Repos/ecommerce-checkout-service/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.Module._resolveFilename (.../node_modules/tsconfig-paths/lib/register.js:75:40)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (.../node_modules/@commercetools/sdk-client-v2/dist/commercetools-sdk-client-v2.cjs.dev.js:180:18)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '.../node_modules/@commercetools/sdk-client-v2/dist/commercetools-sdk-client-v2.cjs.dev.js',
    '.../node_modules/@commercetools/sdk-client-v2/dist/commercetools-sdk-client-v2.cjs.js',
    ...
  ]
}
```

I believe this happens because PR #163 does `require('buffer/')` without ensuring that `buffer` is actually a dependency. 
If I manually install `buffer` in my project myself, the error doesn't happen anymore.

**Comment by jenschude** [comment]
Thanks for the report!

We released 1.0.2 which adds buffer as a dependency.

**Comment by jenschude** [comment]
Btw it was it the root package.json a dependency. But somehow it didn't was added to the client package 🤷‍♂️

**Comment by alessandro-calo-emma** [comment]
Great, thanks for the quick release!
