### ISSUE TITLE
[Question] Unclear error message: Import container key in uri does not exist

### ISSUE THREAD

**Issue by just-L** [commercetools/commercetools-sdk-typescript#494]
We are using importapi-sdk to import the products.
Container created at the begging of the process.
Later in the process call to URL:  `https://import.us-central1.gcp.commercetools.com/project/product-drafts/import-containers/102702999417` returns exception with following message:

``t
Exception: Import container key in uri does not exist
Stack: BadRequest: **Import container key in uri does not exist**
    at createError (C:\home\site\wwwroot\node_modules\@commercetools\sdk-client-v2\dist\commercetools-sdk-client-v2.cjs.dev.js:714:29)
    at C:\home\site\wwwroot\node_modules\@commercetools\sdk-client-v2\dist\commercetools-sdk-client-v2.cjs.dev.js:865:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
``

Does it mean that container wasn't created? Or this message represent something else?

Regards.

**Comment by markus-azer** [comment]
Hi @just-L 

yes that means this container doesn't exist, and after also checking US env `102702999417` doesn't exist.
could you try again to create the container and in case of not created, could you share the `correlationId` (in case not side by the client, its auto created, you should find it in the response headers `x-correlation-id`)
