### ISSUE TITLE
@commercetools/ts-client 2.0 throws javascript error on http error

### ISSUE THREAD

**Issue by mvantellingen** [commercetools/commercetools-sdk-typescript#761]
**Describe the bug**
I previously run into this issue: https://github.com/commercetools/commercetools-sdk-typescript/issues/647 but with the latest version (2.0) we now get the following error:

```
TypeError: Cannot read properties of undefined (reading 'error')
../../../node_modules/.pnpm/@commercetools+ts-client@2.0.0_encoding@0.1.13/node_modules/@commercetools/ts-client/dist/commercetools-ts-client.cjs.dev.js:1461:19
```

I think this is the relevant line https://github.com/commercetools/commercetools-sdk-typescript/blob/b7581b6cce8357bd1d4be47f980ff53f03f0a83b/packages/sdk-client-v3/src/client/client.ts#L179

**To Reproduce**
Do a request which returns an error

**Comment by mvantellingen** [comment]
PS. we (Lab Digital) have a shared slack channel, feel free to reach out to me.

**Comment by Engerim** [comment]
I see a similiar issue but only when I use the `createQueueMiddleware` then we ofc queue a lot of requests and when we exceed the concurrency value of 10 in our case, the res is undefined hte process failed, if I deactivate the queue it works

**Comment by ajimae** [comment]
> PS. we (Lab Digital) have a shared slack channel, feel free to reach out to me.

Hi @mvantellingen 

Thanks for reporting this issue. Can you provide me with more details on the request that caused this error? if possible a code snippet will also work.

Thanks

**Comment by ajimae** [comment]
> I see a similiar issue but only when I use the `createQueueMiddleware` then we ofc queue a lot of requests and when we exceed the concurrency value of 10 in our case, the res is undefined hte process failed, if I deactivate the queue it works

Hi @Engerim 

Can you provide a code snippet that caused this issue, in the mean time I will investigate it to see if I can reproduce it from my end.

Thanks once again for reporting this issue.

**Comment by ajimae** [comment]
Currently working to find the root cause of this issue and I can confirm this issue doesn't exist in version 1.0.0 of the `@commercetools/ts-client`.

I will continue working to fix it.

**Comment by Engerim** [comment]
We are working just with a loop of promises where we send over 100 requests and in the promises and we use the concurrency middleware and set the value to 10 and it fails. it is just happening I will try on monday to replicate the issue in a smaller testcase

**Comment by ajimae** [comment]
Hi @Engerim,

We raised a [PR](https://github.com/commercetools/commercetools-sdk-typescript/pull/777) to fix this issue, once it's merge and we release a new version, this issue should be fixed.

Thanks

**Comment by ajimae** [comment]
This is now fixed, please update to the latest version of the SDK. Thanks

**Comment by miticm** [comment]
Hi @ajimae, I am getting the error using the latest 2.0.4 version `[0] TypeError: Cannot read properties of undefined (reading 'error')
[0]     at /node_modules/@commercetools/ts-client/dist/commercetools-ts-client.cjs.dev.js:1492:19
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`
I am using the withAnonymousSessionFlow and performing some chained calls like this `
    apiRoot
    .inStoreKeyWithStoreKeyValue({ storeKey: xxx" })
    .me()
    .carts()
    .withId({ ID: cartId })
    .post({
      body: {
        version: version,
        actions: [myCartAddLineItemAction],
      },
    })
    .execute()` and when an error occurs, the error above from the SDK will appear

**Comment by ajimae** [comment]
Hi @mitcim,

I would like to know if you experience this error only on version 2.0.4. does it also occur in version prior to 2.0.4, can you check if this error also occur in version 2.0.3?

Thanks

**Comment by miticm** [comment]
Hi @ajimae, 

I also experience this error in 2.0.3 and 2.0.2. I am not using the ConcurrentModificationMiddleware though, so I am not sure if the fix is relevant

Thanks

**Comment by ajimae** [comment]
Hi @miticm

Thanks for confirming the issue also exists in other versions of the SDK. 

I will look into this and make a fix as soon as possible.

I will let you know, once it is done.


Thanks

**Comment by ajimae** [comment]
Hi @miticm 

I have been struggling to reproduce this issue, please can you share the code and configs that triggers this issues?

Preferably the client and the function and methods you are calling for making requests.

Thank you

**Comment by miticm** [comment]
Hi @ajimae, 
```
"@commercetools/checkout-browser-sdk": "^0.7.1",
"@commercetools/platform-sdk": "^7.13.0",
"@commercetools/ts-client": "^2.0.4",
```
here is the Client I use 
```
export const getAnonymousSessionFlowApiRoot = ({
  token,
  refreshToken,
  expirationTime,
}: {
  token: string;
  refreshToken: string;
  expirationTime: number;
}): ApiRoot => {
  //AnonymousAuthMiddlewareOptions type not exist anymore in ts-client sdk
  const anonymousSession: AuthMiddlewareOptions = {
    host: oauthHost,
    projectKey,
    credentials: {
      clientId,
      clientSecret,
    },
    tokenCache: {
      get: () => {
        return {
          token,
          expirationTime,
          refreshToken,
        };
      },
      set: () => {},
    },
    scopes: [`manage_project:${projectKey}`],
  };

  const client = new ClientBuilder().withAnonymousSessionFlow(anonymousSession).withHttpMiddleware(httpOptions).build();
  return createApiBuilderFromCtpClient(client).withProjectKey({ projectKey });
};
```
and here is a call example
```
    apiRoot
    .inStoreKeyWithStoreKeyValue({ storeKey: "au-store" })
    .me()
    .activeCart()
    .get({
      queryArgs: {
        expand: "shippingInfo.shippingMethod",
      },
    })
    .execute();

```
 and it will produce results with TypeError like these
```
[0] TypeError: Cannot read properties of undefined (reading 'error')
[0]     at /node_modules/@commercetools/ts-client/dist/commercetools-ts-client.cjs.dev.js:1492:19
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0]  POST /api/commercetool/cart/activeCart 200 in 1005ms
```
```
[0] TypeError: Cannot read properties of undefined (reading 'error')
[0]     at /node_modules/@commercetools/ts-client/dist/commercetools-ts-client.cjs.dev.js:1492:19
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0]  POST /api/commercetool/cart/addToCart 500 in 1810ms
```

**Comment by ajimae** [comment]
> Hi @ajimae,
> 
> ```
> "@commercetools/checkout-browser-sdk": "^0.7.1",
> "@commercetools/platform-sdk": "^7.13.0",
> "@commercetools/ts-client": "^2.0.4",
> ```
> 
> here is the Client I use
> 
> ```
> export const getAnonymousSessionFlowApiRoot = ({
>   token,
>   refreshToken,
>   expirationTime,
> }: {
>   token: string;
>   refreshToken: string;
>   expirationTime: number;
> }): ApiRoot => {
>   //AnonymousAuthMiddlewareOptions type not exist anymore in ts-client sdk
>   const anonymousSession: AuthMiddlewareOptions = {
>     host: oauthHost,
>     projectKey,
>     credentials: {
>       clientId,
>       clientSecret,
>     },
>     tokenCache: {
>       get: () => {
>         return {
>           token,
>           expirationTime,
>           refreshToken,
>         };
>       },
>       set: () => {},
>     },
>     scopes: [`manage_project:${projectKey}`],
>   };
> 
>   const client = new ClientBuilder().withAnonymousSessionFlow(anonymousSession).withHttpMiddleware(httpOptions).build();
>   return createApiBuilderFromCtpClient(client).withProjectKey({ projectKey });
> };
> ```
> 
> and here is a call example
> 
> ```
>     apiRoot
>     .inStoreKeyWithStoreKeyValue({ storeKey: "au-store" })
>     .me()
>     .activeCart()
>     .get({
>       queryArgs: {
>         expand: "shippingInfo.shippingMethod",
>       },
>     })
>     .execute();
> ```
> 
> and it will produce results with TypeError like these
> 
> ```
> [0] TypeError: Cannot read properties of undefined (reading 'error')
> [0]     at /node_modules/@commercetools/ts-client/dist/commercetools-ts-client.cjs.dev.js:1492:19
> [0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> [0]  POST /api/commercetool/cart/activeCart 200 in 1005ms
> ```
> 
> ```
> [0] TypeError: Cannot read properties of undefined (reading 'error')
> [0]     at /node_modules/@commercetools/ts-client/dist/commercetools-ts-client.cjs.dev.js:1492:19
> [0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> [0]  POST /api/commercetool/cart/addToCart 500 in 1810ms
> ```

Hi @miticm,

I have seen the snippets.

I will take a look at it today and hopefully get it fixed.

Thanks

**Comment by ajimae** [comment]
Hi @miticm,

I have been on this issue for sometime now and I still couldn't reproduce this on my end.

The following is the snippet I used for testing:

```js
const { ClientBuilder } = require('@commercetools/ts-client');
const { createApiBuilderFromCtpClient } = require('@commercetools/platform-sdk')
const fetch = require('node-fetch');

function _tokenCache(val) {
  let initialVal = val
  return {
    get() {
      return initialVal
    },
    set(value) {
      initialVal = value
    }
  }
}

const tokenCache = _tokenCache({ token, expirationTime })
const projectKey = process.env.CTP_PROJECT_KEY;

const authMiddlewareOptions = {
  projectKey,
  host: 'https://auth.europe-west1.gcp.commercetools.com',
  credentials: {
    clientId: process.env.CTP_CLIENT_ID,
    clientSecret: process.env.CTP_CLIENT_SECRET
  },
  tokenCache,
  scopes: [`manage_project:${projectKey}`],
  httpClient: fetch
}

const httpMiddlewareOptions = {
  host: 'https://api.europe-west1.gcp.commercetools.com',
  // includeOriginalRequest: true,
  // maskSensitiveHeaderData: true,
  httpClient: fetch
}

const client = new ClientBuilder()
  .withProjectKey(projectKey)
  .withAnonymousSessionFlow(authMiddlewareOptions)
  .withHttpMiddleware(httpMiddlewareOptions)
  .build();

const apiRoot = createApiBuilderFromCtpClient(client).withProjectKey({ projectKey });

async function exec() {
  // create store
  // return apiRoot
  //   .stores()
  //   .post({ body: { key: 'xxx-test-key' } })
  //   .execute();

  // get carts
  // return apiRoot
  //   .inStoreKeyWithStoreKeyValue({ storeKey: 'xxx-test-key' })
  //   .me()
  //   .carts()
  //   .get({
  //     queryArgs: {
  //       expand: 'shippingInfo.shippingMethod',
  //     },
  //   }).execute();

  // create a cart in store
  // return apiRoot
  //   .inStoreKeyWithStoreKeyValue({ storeKey: 'xxx-test-key' })
  //   .me()
  //   .carts()
  //   .post({
  //     body: {
  //       currency: 'EUR'
  //     }
  //   }).execute();

  // get in-store active cart
  return apiRoot
    .inStoreKeyWithStoreKeyValue({ storeKey: 'xxx-test-key' })
    .me()
    .activeCart()
    .get({
      queryArgs: {
        expand: 'shippingInfo.shippingMethod'
      }
    }).execute();
}

exec()
  .then(data => {
    console.log(data)
  }).catch(e => {
    console.error(e)
  });
  ```
  
This is the error response when the active cart is not found.

<details>
  <summary>Click to expand</summary>

```
 NotFound: URI not found: /{projectKey}/in-store/key=xxx-test-key/me/active-cart
    at createError (/Users/****/workspace/commercetools-sdk-typescript/packages/sdk-client/dist/commercetools-sdk-client-v2.cjs.dev.js:769:29)
    at /Users/****/workspace/commercetools-sdk-typescript/packages/sdk-client/dist/commercetools-sdk-client-v2.cjs.dev.js:940:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 404,
  statusCode: 404,
  status: 404,
  originalRequest: {
    baseUri: 'https://api.europe-west1.gcp.commercetools.com',
    method: 'GET',
    uriTemplate: '/{projectKey}/in-store/key={storeKey}/me/active-cart',
    pathVariables: {
      projectKey: '{projectKey}',
      storeKey: 'xxx-test-key'
    },
    headers: { Authorization: 'Bearer ********' },
    queryParams: undefined,
    uri: '/{projectKey}/in-store/key=xxx-test-key/me/active-cart'
  },
  retryCount: 0,
  headers: [Object: null prototype] {},
  body: {
    statusCode: 404,
    message: 'No active cart exists.',
    errors: [ [Object] ]
  }
}

```
</details>

I would suggest you do one or all the following to see if the issue still persists.

- [ ] Create a new simple and fresh project from scratch.
- [ ] Make a fresh install of the @commercetools/ts-client SDK.
- [ ] Properly check your environment variables
- [ ] If possible try out a new auth flow e.g `ClientCredentialsFlow`.
- [ ] Try out the old client version to see if it works as expected.
- [ ] Add a resolution field to your package.json to ensure the @commercetools/ts-client resolves to version 2.0.3 or newer.
- [ ] Update node version.


Thank you.

**Comment by ajimae** [comment]
Hi @miticm,

I am now able to reproduce this issue. The issue occurs when the `execute()` in the SDK is called concurrently.

I will raise a PR soon to fix this issue.


Thank you.

**Comment by ajimae** [comment]
This should now be [fixed](https://github.com/commercetools/commercetools-sdk-typescript/pull/806)

Don't hesitate to reopen if the issue still persists.

Thank you.

**Comment by miticm** [comment]
Hi @ajimae, the issue still exists after upgrading the packages

**Comment by ajimae** [comment]
Hi, 

We made almost a complete rewrite of the internal logic of the v3 SDK, we just made a new (v2.1.0) release.

You can try to update to the latest version and let us know if this issue still exists.

Thank you.

**Comment by miticm** [comment]
Hi, I tried again today, and it works now, thanks
